### ISSUE TITLE
1389 wave.Error: unknown format: 65534

### ISSUE THREAD

**Issue by sih4sing5hong5** [Sui-Siann-Dataset/Sui-Siann-Dataset#154]
```
it_1     | Traceback (most recent call last):
it_1     |   File "manage.py", line 10, in <module>
it_1     |     execute_from_command_line(sys.argv)
it_1     |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
it_1     |     utility.execute()
it_1     |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 356, in execute
it_1     |     self.fetch_command(subcommand).run_from_argv(self.argv)
it_1     |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
it_1     |     self.execute(*args, **cmd_options)
it_1     |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
it_1     |     output = self.handle(*args, **options)
it_1     |   File "/usr/local/lib/python3.7/site-packages/臺灣言語服務/management/commands/音檔轉Kaldi格式資料.py", line 58, in handle
it_1     |     Q(pk=過渡格式.編號())
it_1     |   File "/usr/local/lib/python3.7/site-packages/臺灣言語服務/Kaldi語料匯出.py", line 46, in 匯出一種語言語料
it_1     |     匯出條件,
it_1     |   File "/usr/local/lib/python3.7/site-packages/臺灣言語服務/Kaldi語料匯出.py", line 203, in _揣影音輸出
it_1     |     音檔長度 = 一筆.聲音檔().時間長度()
it_1     |   File "/usr/local/lib/python3.7/site-packages/臺灣言語服務/models.py", line 56, in 聲音檔
it_1     |     return 聲音檔.對檔案讀(self.影音所在)
it_1     |   File "/usr/local/lib/python3.7/site-packages/臺灣言語工具/語音辨識/聲音檔.py", line 11, in 對檔案讀
it_1     |     with wave.open(音檔所在, 'rb') as wave音檔:
it_1     |   File "/usr/local/lib/python3.7/wave.py", line 510, in open
it_1     |     return Wave_read(f)
it_1     |   File "/usr/local/lib/python3.7/wave.py", line 164, in __init__
it_1     |     self.initfp(f)
it_1     |   File "/usr/local/lib/python3.7/wave.py", line 144, in initfp
it_1     |     self._read_fmt_chunk(chunk)
it_1     |   File "/usr/local/lib/python3.7/wave.py", line 269, in _read_fmt_chunk
it_1     |     raise Error('unknown format: %r' % (wFormatTag,))
it_1     | wave.Error: unknown format: 65534
```

http://wavefilegem.com/how_wave_files_work.html
https://github.com/jiaaro/pydub/issues/134

**Comment by sih4sing5hong5** [comment]
```
>>> for ku in 句表.objects.order_by('id').filter(id__lt=1389):
>>>     print(ku.id)
>>>     ku.重對齊()
```

**Comment by sih4sing5hong5** [comment]
https://github.com/i3thuan5/tai5-uan5_gian5-gi2_kang1-ku7/pull/625

**Comment by Cybernetic1** [comment]
A Chinese web site says that it is due to WAV file format, not the fault of ffmpeg.
The solution is to use the `sox` utility:

    sox input.wav -b 16 -e signed-integer output.wav
